export const mainData = [
  {
    login: "antonio06",
    id: 14540103,
    node_id: "MDQ6VXNlcjE0NTQwMTAz",
    avatar_url: "https://avatars.githubusercontent.com/u/14540103?v=4",
    url: "https://api.github.com/users/antonio06",
    html_url: "https://github.com/antonio06",
    type: "User",
    site_admin: false,
  },
  {
    login: "brauliodiez",
    id: 1457912,
    node_id: "MDQ6VXNlcjE0NTc5MTI=",
    avatar_url: "https://avatars.githubusercontent.com/u/1457912?v=4",
    url: "https://api.github.com/users/brauliodiez",
    html_url: "https://github.com/brauliodiez",
    type: "User",
    site_admin: false,
  },
  {
    login: "Chimalion",
    id: 113333501,
    node_id: "U_kgDOBsFU_Q",
    avatar_url: "https://avatars.githubusercontent.com/u/113333501?v=4",
    url: "https://api.github.com/users/Chimalion",
    html_url: "https://github.com/Chimalion",
    type: "User",
    site_admin: false,
  },
  {
    login: "crsanti",
    id: 13205689,
    node_id: "MDQ6VXNlcjEzMjA1Njg5",
    avatar_url: "https://avatars.githubusercontent.com/u/13205689?v=4",
    url: "https://api.github.com/users/crsanti",
    type: "User",
    site_admin: false,
  },
  {
    login: "fdejesusmazzoni",
    id: 43171355,
    node_id: "MDQ6VXNlcjQzMTcxMzU1",
    avatar_url: "https://avatars.githubusercontent.com/u/43171355?v=4",
    url: "https://api.github.com/users/fdejesusmazzoni",
    html_url: "https://github.com/fdejesusmazzoni",
    type: "User",
    site_admin: false,
  },
  {
    login: "fjcalzado",
    id: 24454225,
    node_id: "MDQ6VXNlcjI0NDU0MjI1",
    avatar_url: "https://avatars.githubusercontent.com/u/24454225?v=4",
    url: "https://api.github.com/users/fjcalzado",
    html_url: "https://github.com/fjcalzado",
    type: "User",
    site_admin: false,
  },
  {
    login: "JaimeSalas",
    id: 7754966,
    node_id: "MDQ6VXNlcjc3NTQ5NjY=",
    avatar_url: "https://avatars.githubusercontent.com/u/7754966?v=4",
    url: "https://api.github.com/users/JaimeSalas",
    html_url: "https://github.com/JaimeSalas",
    type: "User",
    site_admin: false,
  },
  {
    login: "JTrillo",
    id: 33926302,
    node_id: "MDQ6VXNlcjMzOTI2MzAy",
    avatar_url: "https://avatars.githubusercontent.com/u/33926302?v=4",
    url: "https://api.github.com/users/JTrillo",
    html_url: "https://github.com/JTrillo",
    type: "User",
    site_admin: false,
  },
  {
    login: "juanpms2",
    id: 58438522,
    node_id: "MDQ6VXNlcjU4NDM4NTIy",
    avatar_url: "https://avatars.githubusercontent.com/u/58438522?v=4",
    url: "https://api.github.com/users/juanpms2",
    html_url: "https://github.com/juanpms2",
    type: "User",
    site_admin: false,
  },
  {
    login: "manudous",
    id: 67704877,
    node_id: "MDQ6VXNlcjY3NzA0ODc3",
    avatar_url: "https://avatars.githubusercontent.com/u/67704877?v=4",
    url: "https://api.github.com/users/manudous",
    html_url: "https://github.com/manudous",
    type: "User",
    site_admin: false,
  },
  {
    login: "nasdan",
    id: 4374977,
    node_id: "MDQ6VXNlcjQzNzQ5Nzc=",
    avatar_url: "https://avatars.githubusercontent.com/u/4374977?v=4",
    url: "https://api.github.com/users/nasdan",
    html_url: "https://github.com/nasdan",
    type: "User",
    site_admin: false,
  },
  {
    login: "v-borrego",
    id: 43609530,
    node_id: "MDQ6VXNlcjQzNjA5NTMw",
    avatar_url: "https://avatars.githubusercontent.com/u/43609530?v=4",
    url: "https://api.github.com/users/v-borrego",
    html_url: "https://github.com/v-borrego",
    type: "User",
    site_admin: false,
  },
];

export const detailData = [
  {
    login: "antonio06",
    id: 14540103,
    node_id: "MDQ6VXNlcjE0NTQwMTAz",
    avatar_url: "https://avatars.githubusercontent.com/u/14540103?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/antonio06",
    html_url: "https://github.com/antonio06",
    followers_url: "https://api.github.com/users/antonio06/followers",
    following_url:
      "https://api.github.com/users/antonio06/following{/other_user}",
    gists_url: "https://api.github.com/users/antonio06/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/antonio06/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/antonio06/subscriptions",
    organizations_url: "https://api.github.com/users/antonio06/orgs",
    repos_url: "https://api.github.com/users/antonio06/repos",
    events_url: "https://api.github.com/users/antonio06/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/antonio06/received_events",
    type: "User",
    site_admin: false,
    name: "AntonioContrerasRomán",
    company: "@Lemoncode",
    blog: "",
    location: "@Lemoncode",
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 17,
    public_gists: 0,
    followers: 33,
    following: 24,
    created_at: "2015-09-21T06:39:24Z",
    updated_at: "2024-03-15T15:06:46Z",
  },
  {
    login: "brauliodiez",
    id: 1457912,
    node_id: "MDQ6VXNlcjE0NTc5MTI=",
    avatar_url: "https://avatars.githubusercontent.com/u/1457912?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/brauliodiez",
    html_url: "https://github.com/brauliodiez",
    followers_url: "https://api.github.com/users/brauliodiez/followers",
    following_url:
      "https://api.github.com/users/brauliodiez/following{/other_user}",
    gists_url: "https://api.github.com/users/brauliodiez/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/brauliodiez/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/brauliodiez/subscriptions",
    organizations_url: "https://api.github.com/users/brauliodiez/orgs",
    repos_url: "https://api.github.com/users/brauliodiez/repos",
    events_url: "https://api.github.com/users/brauliodiez/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/brauliodiez/received_events",
    type: "User",
    site_admin: false,
    name: "Braulio Diez",
    company: "Lemoncode",
    blog: "http://www.lemoncode.net/",
    location: "Malaga",
    email: null,
    hireable: true,
    bio: "LemonCoder, React dev",
    twitter_username: "braulio_sl",
    public_repos: 67,
    public_gists: 17,
    followers: 158,
    following: 7,
    created_at: "2012-02-21T16:04:15Z",
    updated_at: "2024-02-03T22:45:03Z",
  },
  {
    login: "Chimalion",
    id: 113333501,
    node_id: "U_kgDOBsFU_Q",
    avatar_url: "https://avatars.githubusercontent.com/u/113333501?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Chimalion",
    html_url: "https://github.com/Chimalion",
    followers_url: "https://api.github.com/users/Chimalion/followers",
    following_url:
      "https://api.github.com/users/Chimalion/following{/other_user}",
    gists_url: "https://api.github.com/users/Chimalion/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Chimalion/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Chimalion/subscriptions",
    organizations_url: "https://api.github.com/users/Chimalion/orgs",
    repos_url: "https://api.github.com/users/Chimalion/repos",
    events_url: "https://api.github.com/users/Chimalion/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Chimalion/received_events",
    type: "User",
    site_admin: false,
    name: "Miguel Chimali",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 9,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: "2022-09-12T06:41:17Z",
    updated_at: "2024-01-25T15:54:31Z",
  },
  {
    login: "crsanti",
    id: 13205689,
    node_id: "MDQ6VXNlcjEzMjA1Njg5",
    avatar_url: "https://avatars.githubusercontent.com/u/13205689?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/crsanti",
    html_url: "https://github.com/crsanti",
    followers_url: "https://api.github.com/users/crsanti/followers",
    following_url:
      "https://api.github.com/users/crsanti/following{/other_user}",
    gists_url: "https://api.github.com/users/crsanti/gists{/gist_id}",
    starred_url: "https://api.github.com/users/crsanti/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/crsanti/subscriptions",
    organizations_url: "https://api.github.com/users/crsanti/orgs",
    repos_url: "https://api.github.com/users/crsanti/repos",
    events_url: "https://api.github.com/users/crsanti/events{/privacy}",
    received_events_url: "https://api.github.com/users/crsanti/received_events",
    type: "User",
    site_admin: false,
    name: "Santiago Camargo Rodríguez",
    company: null,
    blog: "",
    location: "Málaga",
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 17,
    public_gists: 6,
    followers: 33,
    following: 0,
    created_at: "2015-07-06T17:48:11Z",
    updated_at: "2024-03-15T10:47:52Z",
  },
  {
    login: "fdejesusmazzoni",
    id: 43171355,
    node_id: "MDQ6VXNlcjQzMTcxMzU1",
    avatar_url: "https://avatars.githubusercontent.com/u/43171355?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/fdejesusmazzoni",
    html_url: "https://github.com/fdejesusmazzoni",
    followers_url: "https://api.github.com/users/fdejesusmazzoni/followers",
    following_url:
      "https://api.github.com/users/fdejesusmazzoni/following{/other_user}",
    gists_url: "https://api.github.com/users/fdejesusmazzoni/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/fdejesusmazzoni/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/fdejesusmazzoni/subscriptions",
    organizations_url: "https://api.github.com/users/fdejesusmazzoni/orgs",
    repos_url: "https://api.github.com/users/fdejesusmazzoni/repos",
    events_url: "https://api.github.com/users/fdejesusmazzoni/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/fdejesusmazzoni/received_events",
    type: "User",
    site_admin: false,
    name: "Francisco Javier de Jesús Mazzoni",
    company: "@Lemoncode ",
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 5,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: "2018-09-11T10:37:49Z",
    updated_at: "2024-03-19T08:37:59Z",
  },
  {
    login: "fjcalzado",
    id: 24454225,
    node_id: "MDQ6VXNlcjI0NDU0MjI1",
    avatar_url: "https://avatars.githubusercontent.com/u/24454225?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/fjcalzado",
    html_url: "https://github.com/fjcalzado",
    followers_url: "https://api.github.com/users/fjcalzado/followers",
    following_url:
      "https://api.github.com/users/fjcalzado/following{/other_user}",
    gists_url: "https://api.github.com/users/fjcalzado/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/fjcalzado/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/fjcalzado/subscriptions",
    organizations_url: "https://api.github.com/users/fjcalzado/orgs",
    repos_url: "https://api.github.com/users/fjcalzado/repos",
    events_url: "https://api.github.com/users/fjcalzado/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/fjcalzado/received_events",
    type: "User",
    site_admin: false,
    name: "Javier Calzado",
    company: "@Lemoncode",
    blog: "",
    location: "Málaga",
    email: null,
    hireable: null,
    bio: "Coder, frontender, engineer and passionate hobbyist and traveler",
    twitter_username: "fjcalzadosp",
    public_repos: 21,
    public_gists: 3,
    followers: 55,
    following: 21,
    created_at: "2016-12-08T11:07:44Z",
    updated_at: "2024-03-14T11:03:10Z",
  },
  {
    login: "JaimeSalas",
    id: 7754966,
    node_id: "MDQ6VXNlcjc3NTQ5NjY=",
    avatar_url: "https://avatars.githubusercontent.com/u/7754966?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/JaimeSalas",
    html_url: "https://github.com/JaimeSalas",
    followers_url: "https://api.github.com/users/JaimeSalas/followers",
    following_url:
      "https://api.github.com/users/JaimeSalas/following{/other_user}",
    gists_url: "https://api.github.com/users/JaimeSalas/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/JaimeSalas/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/JaimeSalas/subscriptions",
    organizations_url: "https://api.github.com/users/JaimeSalas/orgs",
    repos_url: "https://api.github.com/users/JaimeSalas/repos",
    events_url: "https://api.github.com/users/JaimeSalas/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/JaimeSalas/received_events",
    type: "User",
    site_admin: false,
    name: "Jaime Salas",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 57,
    public_gists: 0,
    followers: 53,
    following: 1,
    created_at: "2014-05-31T15:20:34Z",
    updated_at: "2024-03-22T09:59:22Z",
  },
  {
    login: "JTrillo",
    id: 33926302,
    node_id: "MDQ6VXNlcjMzOTI2MzAy",
    avatar_url: "https://avatars.githubusercontent.com/u/33926302?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/JTrillo",
    html_url: "https://github.com/JTrillo",
    followers_url: "https://api.github.com/users/JTrillo/followers",
    following_url:
      "https://api.github.com/users/JTrillo/following{/other_user}",
    gists_url: "https://api.github.com/users/JTrillo/gists{/gist_id}",
    starred_url: "https://api.github.com/users/JTrillo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/JTrillo/subscriptions",
    organizations_url: "https://api.github.com/users/JTrillo/orgs",
    repos_url: "https://api.github.com/users/JTrillo/repos",
    events_url: "https://api.github.com/users/JTrillo/events{/privacy}",
    received_events_url: "https://api.github.com/users/JTrillo/received_events",
    type: "User",
    site_admin: false,
    name: "Joaquín Trillo",
    company: "Lemoncode",
    blog: "",
    location: "Málaga, Spain",
    email: null,
    hireable: true,
    bio: "Java / JS / TS developer, currently working @Lemoncode. I also like collaborating in open-source projects.",
    twitter_username: null,
    public_repos: 20,
    public_gists: 0,
    followers: 4,
    following: 2,
    created_at: "2017-11-23T09:13:59Z",
    updated_at: "2024-02-26T16:33:31Z",
  },
  {
    login: "juanpms2",
    id: 58438522,
    node_id: "MDQ6VXNlcjU4NDM4NTIy",
    avatar_url: "https://avatars.githubusercontent.com/u/58438522?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/juanpms2",
    html_url: "https://github.com/juanpms2",
    followers_url: "https://api.github.com/users/juanpms2/followers",
    following_url:
      "https://api.github.com/users/juanpms2/following{/other_user}",
    gists_url: "https://api.github.com/users/juanpms2/gists{/gist_id}",
    starred_url: "https://api.github.com/users/juanpms2/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/juanpms2/subscriptions",
    organizations_url: "https://api.github.com/users/juanpms2/orgs",
    repos_url: "https://api.github.com/users/juanpms2/repos",
    events_url: "https://api.github.com/users/juanpms2/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/juanpms2/received_events",
    type: "User",
    site_admin: false,
    name: "Juan Pablo Martínez",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: "Frontend developer",
    twitter_username: null,
    public_repos: 22,
    public_gists: 0,
    followers: 2,
    following: 1,
    created_at: "2019-12-02T16:46:20Z",
    updated_at: "2023-09-28T06:31:14Z",
  },
  {
    login: "manudous",
    id: 67704877,
    node_id: "MDQ6VXNlcjY3NzA0ODc3",
    avatar_url: "https://avatars.githubusercontent.com/u/67704877?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/manudous",
    html_url: "https://github.com/manudous",
    followers_url: "https://api.github.com/users/manudous/followers",
    following_url:
      "https://api.github.com/users/manudous/following{/other_user}",
    gists_url: "https://api.github.com/users/manudous/gists{/gist_id}",
    starred_url: "https://api.github.com/users/manudous/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/manudous/subscriptions",
    organizations_url: "https://api.github.com/users/manudous/orgs",
    repos_url: "https://api.github.com/users/manudous/repos",
    events_url: "https://api.github.com/users/manudous/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/manudous/received_events",
    type: "User",
    site_admin: false,
    name: "Manolo Dorado",
    company: "Lemoncode",
    blog: "",
    location: "Alcalá del Valle",
    email: null,
    hireable: null,
    bio: null,
    twitter_username: "manudose",
    public_repos: 95,
    public_gists: 0,
    followers: 9,
    following: 23,
    created_at: "2020-07-01T16:56:57Z",
    updated_at: "2024-02-21T12:55:41Z",
  },
  {
    login: "nasdan",
    id: 4374977,
    node_id: "MDQ6VXNlcjQzNzQ5Nzc=",
    avatar_url: "https://avatars.githubusercontent.com/u/4374977?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nasdan",
    html_url: "https://github.com/nasdan",
    followers_url: "https://api.github.com/users/nasdan/followers",
    following_url: "https://api.github.com/users/nasdan/following{/other_user}",
    gists_url: "https://api.github.com/users/nasdan/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nasdan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nasdan/subscriptions",
    organizations_url: "https://api.github.com/users/nasdan/orgs",
    repos_url: "https://api.github.com/users/nasdan/repos",
    events_url: "https://api.github.com/users/nasdan/events{/privacy}",
    received_events_url: "https://api.github.com/users/nasdan/received_events",
    type: "User",
    site_admin: false,
    name: null,
    company: "Lemoncode",
    blog: "http://www.lemoncode.net/",
    location: "Málaga (Spain)",
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 21,
    public_gists: 0,
    followers: 47,
    following: 3,
    created_at: "2013-05-08T09:16:53Z",
    updated_at: "2024-01-24T14:19:39Z",
  },
  {
    login: "v-borrego",
    id: 43609530,
    node_id: "MDQ6VXNlcjQzNjA5NTMw",
    avatar_url: "https://avatars.githubusercontent.com/u/43609530?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/v-borrego",
    html_url: "https://github.com/v-borrego",
    followers_url: "https://api.github.com/users/v-borrego/followers",
    following_url:
      "https://api.github.com/users/v-borrego/following{/other_user}",
    gists_url: "https://api.github.com/users/v-borrego/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/v-borrego/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/v-borrego/subscriptions",
    organizations_url: "https://api.github.com/users/v-borrego/orgs",
    repos_url: "https://api.github.com/users/v-borrego/repos",
    events_url: "https://api.github.com/users/v-borrego/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/v-borrego/received_events",
    type: "User",
    site_admin: false,
    name: "Víctor Borrego Pérez",
    company: "Lemoncode",
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: "Lemoncoder 🦁 Frontend Developer, hooked to React and Svelte 🚀\r\n\r\n\r\nWebpack, rollup, vite, module federation, microfrontends: javascript powa! 💪",
    twitter_username: null,
    public_repos: 14,
    public_gists: 0,
    followers: 14,
    following: 5,
    created_at: "2018-09-26T13:01:00Z",
    updated_at: "2024-03-22T10:01:22Z",
  },
];
